EVALUATION_SCHEMA = {
    "name": "crisis_decision_evaluation",
    "schema": {
        "type": "object",
        "properties": {
            "decision_quality": {"type": "integer", "minimum": 0, "maximum": 100},
            "reputation_delta": {"type": "integer", "minimum": -30, "maximum": 30},
            "legal_risk_delta": {"type": "integer", "minimum": -30, "maximum": 30},
            "media_pressure_delta": {"type": "integer", "minimum": -30, "maximum": 30},
            "employee_trust_delta": {"type": "integer", "minimum": -30, "maximum": 30},
            "regulatory_risk_delta": {"type": "integer", "minimum": -30, "maximum": 30},
            "financial_risk_delta": {"type": "integer", "minimum": -30, "maximum": 30},
            "strengths": {"type": "array", "items": {"type": "string"}},
            "weaknesses": {"type": "array", "items": {"type": "string"}},
            "stakeholder_reactions": {
                "type": "object",
                "properties": {
                    "media": {"type": "string"},
                    "customers": {"type": "string"},
                    "employees": {"type": "string"},
                    "regulators": {"type": "string"},
                    "investors": {"type": "string"},
                },
                "required": ["media", "customers", "employees", "regulators", "investors"],
                "additionalProperties": False,
            },
            "next_context": {"type": "string"},
            "recommended_next_action": {"type": "string"},
        },
        "required": [
            "decision_quality",
            "reputation_delta",
            "legal_risk_delta",
            "media_pressure_delta",
            "employee_trust_delta",
            "regulatory_risk_delta",
            "financial_risk_delta",
            "strengths",
            "weaknesses",
            "stakeholder_reactions",
            "next_context",
            "recommended_next_action",
        ],
        "additionalProperties": False,
    },
}
